#cloud-config
package_update: true
package_upgrade: true
snap:
    commands:
      00: snap install yq
      01: snap install jq
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}
