#cloud-config
package_update: true
package_upgrade: true
users:
  - name: deployer
    groups: [ sudo ]
    sudo: [ "ALL=(ALL) ALL" ]
    shell: /bin/bash
    ssh_import_id: greyhoundforty
    passwd: ${password_hash}
    ssh-authorized-keys:
    - '${generated_key}'
packages:
    - python
    - python-apt
    - python3-apt
    - build-essential
    - unzip
    - jq
    - git
snap:
    commands:
      00: snap install yq
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}