---
  - hosts: instances
    vars_files:
      deployment_vars.yml
    tasks:
      - name: Set consul client environment variable 
        blockinfile:
          path: /root/.bashrc
          block: export CONSUL_HTTP_ADDR="http://{{ ansible_ens3.ipv4.address }}:8500"
      - name: Copy server config to /etc/consul.d/server.hcl
        copy:
          src: ../templates/server.hcl
          dest: /etc/consul.d/server.hcl
          owner: consul
          group: consul
          mode: '0640'
      - name: Template consul client file 
        template:
          src: ../templates/consul-client.j2
          dest: /etc/consul.d/consul.hcl
          owner: consul
          group: consul
          mode: '0640'
      - name: Reset consul directory permissions
        file:
          path: /etc/consul.d
          state: directory
          mode: '755'
          owner: consul
          group: consul
      - name: enable consul service and start it
        systemd:
          name: consul.service
          enabled: yes
          state: started
      - name: Reboot machine
        reboot:
